# render.yaml
services:
  - type: web
    name: picoclaw
    runtime: image
    image:
      url: ghcr.io/sipeed/picoclaw:latest
    dockerCommand: picoclaw gateway
    envVars:
      - key: PICOCLAW_CONFIG_JSON
        value: |
          {
            "model_list": [
              {
                "model_name": "gpt-4o-mini",
                "model": "openrouter/free",
                "api_key": "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"
              }
            ],
            "agents": {
              "defaults": {
                "workspace": "/data/picoclaw/workspace",
                "model": "openrouter/free",
                "restrict_to_workspace": true
              }
            }
          }
        sync: false
    disks:
      - name: picoclaw-data
        mountPath: /data
        sizeGB: 1
